# Introduction

# Matériel et méthode

## Echantillonage 
### 1. Zone d'étude

Notre étude s’est déroulée sur des parcelles de la forêt de Régina Saint Georges, située dans la zone Est de la Guyane française. D’une superficie de 375 446 ha, cette forêt appartient au domaine privé de l’Etat français et est principalement gérée par l’Office National des Forêts (ONF) (+ la direction régionale de Guyane, l’Unité territoriale de Cayenne et les Triages de Régina sud et de St Georges).
Etant divisée en 24 secteurs forestiers (suivant principalement les limites naturelles du terrain), nos échantillonnages se sont portés sur 2 d’entre eux : HKO (Haute Kourouaïe) et MAW (Maweyo) de superficie respectives de 9 671 et 5 769 ha. 

Dans ces zones géographiques, la température moyenne est de 27°C, l’humidité moyenne vraie de 82% et les précipitations moyennes annuelles sont comprises entre 3488 et 3806mm.
Les placettes de 5m de diamètre furent identifiées sur place grâce aux données satellites de l’application QField. On retrouve parmi elles 4 types distincts :

-	Cloisonnement : L’échantillonnage s’est déroulé sur un chemin ayant permis auparavant la circulation d’engins forestiers
-	Canopée fermée : L’échantillonnage s’est déroulé sous un couvert végétal dense (caractérisé par un endroit sombre)
-	Houppier : L’échantillonnage s’est déroulé sous le houppier d’un grand arbre
-	Souche : L’échantillonnage s’est déroulé près d’une souche d’une espèce d’intérêt
Les souches ainsi que leur désignation ont pu être identifiées par des points spécifiques sur l’application QField.


## 2. Espèces d'intérêt 

11 espèces d’intérêt forestier (Annexe 1) furent dans un premier temps identifiées à l’œil nu suivant différents critères. 
Tout d’abord, seuls les individus d’une hauteur supérieure à 30cm et de diamètre inférieur à 10cm furent répertoriés, car la régénération ne concerne pas directement les gros arbres (qui furent, par ailleurs, déjà inventoriés). De plus, le centre de la placette fut représenté par une tige d’un individu (d’intérêt où non) et les individus répertoriés se trouvèrent dans un rayon de 5m à partir de cet individu.
L’identification des espèces a pu être réalisée selon des critères d’identification phénotypiques en se basant sur la morphologie des feuilles :
-	Type de feuille (simple ou composée)
-	Disposition des feuilles et folioles (alternes ou opposées / paripennées ou imparipennées)
-	Forme des feuilles (acuminée, obtus, ovales etc.)
-	Type de bord des feuilles (entier, serrulé etc.)
-	Couleur des feuilles (face inférieure argentée)
-	Nervation (pennée, arquée, transverse, parallèles etc.)
-	Présence ou absence de poils, latex, point noir sur le rachis, odeur particulière (poivre etc.)
Mais aussi des tiges et troncs :
-	Présence ou absence de poils
-	Modèles architecturaux
-	Couleur de l’écorce, écoulement d’exsudat, odeur particulière
Les espèces d’intérêt étant assez différentes morphologiquement et plutôt facilement distinguables des autres, les risques de confusion furent assez faibles entre celles-ci. Cependant, certaines d’entre elles comme le Grignon furent similaires à beaucoup d’autres et leur détection fut plus délicate.
Lorsque qu’un individu appartenant à une espèce d’intérêt fut détecté, différentes variables furent mesurées sur celui-ci, parmi elles :
-	La hauteur (en cm) entre le sol et la dernière feuille vivante grâce à un mètre ruban
-	Le diamètre (en cm) à hauteur de poitrine (DHP)
-	L’azimut par rapport à un individu central (en ??) grâce à une boussole
-	La distance : supérieure (+) ou inférieure (-) à 2,5m de l’individu central
-	La hauteur (en cm) des 3 individus les plus hauts de la parcelle détectée avec un télémètre
-	Le type de placette (cloisonnement, houppier, souche, canopée fermée)
-	La distance de certaines placettes par rapport aux espèces mères 
L’ensemble de ces données fut répertorié sur le logiciel Microsoft Excel grâce à une tablette étanche emmenée sur le terrain. Ces données furent ensuite exportées dans le logiciel R et R Studio afin de subir un traitement statistique.

## Analyses statistiques

Les données obtenues à l’issue des 4 semaines d’échantillonnage sont toutes des variables aléatoires, qui peuvent être classées en 4 différents types : Quantitative continue (diamètre et hauteur), quantitative discrète (hauteur des 3 plus grands individus), qualitative ordinale (distance de l’individu central) et qualitative nominale (type de placette, azimut).
Au total, xx parcelles furent échantillonnées ainsi que xx individus suivant xx variables. 
Certaines d’entre elles furent regroupées afin de faciliter les analyses statistiques.
Ensuite, des tests telle que la régression Zero-Inflated Poisson furent effectués. 

## Rédaction

Ce présent rapport fut rédigé à l’aide de l’hébergeur GitHub via l’interface R Studio.

# Résultats

# Discussion
